[package]
name = "nocom_lending_pool"
type = "contract"
authors = ["Jack Gilcrest"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.2", directory = "noir-projects/aztec-nr/aztec" }
token_contract = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "v3.0.0-devnet.2", directory = "src/token_contract" }
mock_price_feed = { path = "../price_oracle" }
poseidon = { git = "https:/github.com/noir-lang/poseidon", tag = "v0.1.1" }
schnorr = { git = "https://github.com/noir-lang/schnorr", tag = "v0.1.3" }

