[package]
name = "nocom_escrow"
type = "contract"
authors = ["Jack Gilcrest"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.2", directory = "noir-projects/aztec-nr/aztec" }
token_contract = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "v3.0.0-devnet.2", directory = "src/token_contract" }
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }
nocom_stable_pool = { path = "../stable_pool" }
